services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      # Add any other environment variables your Flask app needs
    
networks:
  app-network:
    driver: bridge
